"""altering campaigns

Revision ID: 1253986357bc
Revises: 6feba98d68ee
Create Date: 2026-07-31 23:34:49.448822

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1253986357bc"
down_revision: Union[str, Sequence[str], None] = "6feba98d68ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("campaigns", "end_date", existing_type=sa.DATE(), nullable=True)
    op.create_unique_constraint(None, "campaigns", ["campaign_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "campaigns", type_="unique")
    op.alter_column("campaigns", "end_date", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
