"""describe change

Revision ID: 39eeb125ad31
Revises: 460c162d63d7
Create Date: 2026-07-30 16:36:56.244032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39eeb125ad31"
down_revision: Union[str, Sequence[str], None] = "460c162d63d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("brand_name", sa.String(length=100), nullable=False),
        sa.Column("brand_owner", sa.String(length=150), nullable=True),
        sa.Column("country_of_origin", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("brand_id"),
        sa.UniqueConstraint("brand_name"),
    )
    op.create_table(
        "calendar_dim",
        sa.Column("calendar_date", sa.Date(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("quarter", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("month_name", sa.String(length=20), nullable=False),
        sa.Column("week_of_year", sa.Integer(), nullable=False),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("day_name", sa.String(length=20), nullable=False),
        sa.Column("is_weekend", sa.Boolean(), nullable=False),
        sa.Column("is_prime_day", sa.Boolean(), nullable=False),
        sa.Column("is_black_friday", sa.Boolean(), nullable=False),
        sa.Column("is_cyber_monday", sa.Boolean(), nullable=False),
        sa.Column("is_christmas", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("calendar_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_dim")
    op.drop_table("brands")
    # ### end Alembic commands ###
