"""create marketplaces

Revision ID: 460c162d63d7
Revises:
Create Date: 2026-07-30 15:32:03.593732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "460c162d63d7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "marketplaces",
        sa.Column("marketplace_id", sa.Integer(), nullable=False),
        sa.Column("marketplace_code", sa.String(length=10), nullable=False),
        sa.Column("marketplace_name", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("marketplace_id"),
        sa.UniqueConstraint("marketplace_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("marketplaces")
    # ### end Alembic commands ###
