"""unique constraint in product_category

Revision ID: 6feba98d68ee
Revises: 9e9024730138
Create Date: 2026-07-31 23:08:33.526110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6feba98d68ee"
down_revision: Union[str, Sequence[str], None] = "9e9024730138"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_category_parent",
        "product_categories",
        ["category_name", "parent_category_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_category_parent", "product_categories", type_="unique")
    # ### end Alembic commands ###
