"""altering campaigns

Revision ID: 9d1075c2618c
Revises: b14786cb478e
Create Date: 2026-08-01 00:03:44.812114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9d1075c2618c"
down_revision: Union[str, Sequence[str], None] = "b14786cb478e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "campaigns",
        "match_type",
        existing_type=mysql.ENUM(
            "BROAD", "PHRASE", "EXACT", "PRODUCT_TARGETING", "CATEGORY_TARGETING"
        ),
        nullable=True,
    )
    op.alter_column(
        "campaigns",
        "campaign_state",
        existing_type=mysql.ENUM("ENABLED", "PAUSED", "ARCHIVED"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "campaigns",
        "campaign_state",
        existing_type=mysql.ENUM("ENABLED", "PAUSED", "ARCHIVED"),
        nullable=True,
    )
    op.alter_column(
        "campaigns",
        "match_type",
        existing_type=mysql.ENUM(
            "BROAD", "PHRASE", "EXACT", "PRODUCT_TARGETING", "CATEGORY_TARGETING"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
