"""initial schema

Revision ID: 9e9024730138
Revises:
Create Date: 2026-07-31 22:40:24.186229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e9024730138"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("brand_name", sa.String(length=100), nullable=False),
        sa.Column("brand_owner", sa.String(length=150), nullable=True),
        sa.Column("country_of_origin", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("brand_id"),
        sa.UniqueConstraint("brand_name"),
    )
    op.create_table(
        "calendar_dim",
        sa.Column("calendar_date", sa.Date(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("quarter", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("month_name", sa.String(length=20), nullable=False),
        sa.Column("week_of_year", sa.Integer(), nullable=False),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("day_name", sa.String(length=20), nullable=False),
        sa.Column("is_weekend", sa.Boolean(), nullable=False),
        sa.Column("is_prime_day", sa.Boolean(), nullable=False),
        sa.Column("is_black_friday", sa.Boolean(), nullable=False),
        sa.Column("is_cyber_monday", sa.Boolean(), nullable=False),
        sa.Column("is_christmas", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("calendar_date"),
    )
    op.create_table(
        "marketplaces",
        sa.Column("marketplace_id", sa.Integer(), nullable=False),
        sa.Column("marketplace_code", sa.String(length=10), nullable=False),
        sa.Column("marketplace_name", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("marketplace_id"),
        sa.UniqueConstraint("marketplace_code"),
    )
    op.create_table(
        "portfolios",
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("portfolio_name", sa.String(length=100), nullable=False),
        sa.Column("manager_name", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("portfolio_id"),
    )
    op.create_table(
        "product_categories",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("category_name", sa.String(length=100), nullable=False),
        sa.Column("parent_category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["product_categories.category_id"],
        ),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_table(
        "search_terms",
        sa.Column("search_term_id", sa.Integer(), nullable=False),
        sa.Column("search_term", sa.String(length=255), nullable=False),
        sa.Column("search_volume", sa.Integer(), nullable=False),
        sa.Column("competition", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("search_term_id"),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("asin", sa.String(length=20), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("launch_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.brand_id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.category_id"],
        ),
        sa.PrimaryKeyConstraint("product_id"),
        sa.UniqueConstraint("asin"),
        sa.UniqueConstraint("sku"),
    )
    op.create_table(
        "campaigns",
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("campaign_name", sa.String(length=255), nullable=False),
        sa.Column(
            "campaign_goal",
            sa.Enum(
                "SALES",
                "BRAND_AWARENESS",
                "PRODUCT_LAUNCH",
                "TRAFFIC",
                "STORE_VISITS",
                name="campaigngoal",
            ),
            nullable=False,
        ),
        sa.Column(
            "campaign_type",
            sa.Enum(
                "SPONSORED_PRODUCTS",
                "SPONSORED_BRANDS",
                "SPONSORED_DISPLAY",
                name="campaigntype",
            ),
            nullable=False,
        ),
        sa.Column(
            "targeting_type",
            sa.Enum("AUTO", "MANUAL", name="targetingtype"),
            nullable=False,
        ),
        sa.Column(
            "match_type",
            sa.Enum(
                "BROAD",
                "PHRASE",
                "EXACT",
                "PRODUCT_TARGETING",
                "CATEGORY_TARGETING",
                name="matchtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "campaign_state",
            sa.Enum("ENABLED", "PAUSED", "ARCHIVED", name="campaignstate"),
            nullable=False,
        ),
        sa.Column("marketplace_id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("daily_budget", sa.Float(), nullable=False),
        sa.Column(
            "bidding_strategy",
            sa.Enum(
                "DYNAMIC_DOWN",
                "DYNAMIC_UP_AND_DOWN",
                "FIXED_BIDS",
                name="biddingstrategy",
            ),
            nullable=False,
        ),
        sa.Column(
            "placement",
            sa.Enum(
                "TOP_OF_SEARCH", "REST_OF_SEARCH", "PRODUCT_PAGES", name="placement"
            ),
            nullable=False,
        ),
        sa.Column(
            "optimization_strategy",
            sa.Enum(
                "MAXIMISE_CLICKS",
                "MAXIMISE_CONVERSIONS",
                "TARGET_ACOS",
                "TARGET_ROAS",
                "MANUAL",
                name="optimizationstrategy",
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="priority"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplaces.marketplace_id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.portfolio_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
        ),
        sa.PrimaryKeyConstraint("campaign_id"),
    )
    op.create_table(
        "campaign_daily_metrics",
        sa.Column("metric_id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("spend", sa.Float(), nullable=False),
        sa.Column("orders", sa.Integer(), nullable=False),
        sa.Column("orders_7d", sa.Integer(), nullable=False),
        sa.Column("orders_14d", sa.Integer(), nullable=False),
        sa.Column("orders_30d", sa.Integer(), nullable=False),
        sa.Column("units_sold", sa.Integer(), nullable=False),
        sa.Column("sales", sa.Float(), nullable=False),
        sa.Column("sales_7d", sa.Float(), nullable=False),
        sa.Column("sales_14d", sa.Float(), nullable=False),
        sa.Column("sales_30d", sa.Float(), nullable=False),
        sa.Column("new_to_brand_orders", sa.Integer(), nullable=False),
        sa.Column("new_to_brand_sales", sa.Float(), nullable=False),
        sa.Column("new_to_brand_sales_percentage", sa.Float(), nullable=False),
        sa.Column("cpc", sa.Float(), nullable=False),
        sa.Column("cpm", sa.Float(), nullable=False),
        sa.Column("ctr", sa.Float(), nullable=False),
        sa.Column("conversion_rate", sa.Float(), nullable=False),
        sa.Column("aov", sa.Float(), nullable=False),
        sa.Column("acos", sa.Float(), nullable=False),
        sa.Column("roas", sa.Float(), nullable=False),
        sa.Column("roi", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.campaign_id"],
        ),
        sa.PrimaryKeyConstraint("metric_id"),
        sa.UniqueConstraint(
            "campaign_id", "report_date", name="uq_campaign_report_date"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("campaign_daily_metrics")
    op.drop_table("campaigns")
    op.drop_table("products")
    op.drop_table("search_terms")
    op.drop_table("product_categories")
    op.drop_table("portfolios")
    op.drop_table("marketplaces")
    op.drop_table("calendar_dim")
    op.drop_table("brands")
    # ### end Alembic commands ###
