"""altering campaigns

Revision ID: b14786cb478e
Revises: 1253986357bc
Create Date: 2026-08-01 00:02:19.868339

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b14786cb478e"
down_revision: Union[str, Sequence[str], None] = "1253986357bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "campaigns",
        "campaign_state",
        existing_type=mysql.ENUM("ENABLED", "PAUSED", "ARCHIVED"),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "campaigns",
        "campaign_state",
        existing_type=mysql.ENUM("ENABLED", "PAUSED", "ARCHIVED"),
        nullable=False,
    )
    # ### end Alembic commands ###
