name: Terraform

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"

  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug GitHub context
        run: |
            echo "Repository: $GITHUB_REPOSITORY"
            echo "Ref: $GITHUB_REF"
            echo "Event: $GITHUB_EVENT_NAME"
            echo "Actor: $GITHUB_ACTOR"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::666809320083:role/GitHubActionsTerraformRole
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
